export const aircraftOptions = [
    {
      model: "A220-100",
      family: "Airbus",
      seat_capacity: 133,
      applicable_routes: "1,2,3,4,5,6,7,8,9,10,11,12"
    },
    {
      model: "A320neo",
      family: "Airbus",
      seat_capacity: 180,
      applicable_routes: "3,4,5,6,7,8"
    },
    {
      model: "ATR 72-600",
      family: "Firefly",
      seat_capacity: 72,
      applicable_routes: "13,14,15,16"
    },
  ];


  export const routeOptions = [
    { name: "Bacolod–Silay Airport", code: "BCD", location: "Bacolod" },
    { name: "Bancasi Airport", code: "BXU", location: "Butuan" },
    { name: "Basco Airport", code: "BSO", location: "Batanes" },
    { name: "Bicol International Airport", code: "DRP", location: "Albay" },
    { name: "Bohol–Panglao International Airport (New Bohol Int'l.)", code: "TAG", location: "Bohol" },
    { name: "Catarman National Airport", code: "CRM", location: "Catarman" },
    { name: "Cauayan Airport", code: "CYZ", location: "Isabela" },
    { name: "Calbayog Airport", code: "CYP", location: "Samar" },
    { name: "Camiguin Airport", code: "CGM", location: "Camiguin" },
    { name: "Cotabato Airport (Awang Airport)", code: "CBO", location: "Maguindanao del Norte" },
    { name: "Daniel Z. Romualdez Airport (Tacloban City Airport)", code: "TAC", location: "Tacloban" },
    { name: "Dipolog Airport", code: "DPL", location: "Zamboanga, Dipolog" },
    { name: "Dumaguete–Sibulan Airport", code: "DGT", location: "Dumageuete" },
    { name: "Evelio B. Javier Airport (Antique/San Jose Airport)", code: "EUQ", location: "San Jose" },
    { name: "Francisco B. Reyes Airport (Busuanga Airport)", code: "USU", location: "Coron" },
    { name: "Francisco Bangoy International Airport", code: "DVO", location: "Davao City" },
    { name: "General Santos International Airport (Tambler Airport)", code: "GES", location: "General Santos" },
    { name: "Godofredo P. Ramos Airport (Caticlan/Boracay Airport)", code: "MPH", location: "Aklan" },
    { name: "Iloilo International Airport", code: "ILO", location: "Iloilo" },
    { name: "Jolo Airport", code: "JOL", location: "Jolo, Sulu" },
    { name: "Kalibo International Airport", code: "KLO", location: "Kalibo" },
    { name: "Laoag International Airport", code: "LAO", location: "Laoag" },
    { name: "Laguindingan Airport", code: "CGY", location: "Laguindingan" },
    { name: "Labo Airport (Ozamiz Airport)", code: "OZC", location: "Ozamiz" },
    { name: "Loakan Airport", code: "BAG", location: "Baguio" },
    { name: "Mactan–Cebu International Airport", code: "CEB", location: "Cebu" },
    { name: "Marinduque Airport", code: "MRQ", location: "Marinduque" },
    { name: "Moises R. Espinosa Airport (Masbate Airport)", code: "MBT", location: "Masbate" },
    { name: "Naga Airport", code: "WNP", location: "Camarines Sur" },
    { name: "Ninoy Aquino International Airport", code: "MNL", location: "Manila" },
    { name: "Ormoc Airport", code: "OMC", location: "Ormoc" },
    { name: "Pagadian Airport", code: "PAG", location: "Pagadian" },
    { name: "Puerto Princesa International Airport", code: "PPS", location: "Puerto Princesa" },
    { name: "Roxas Airport", code: "RXS", location: "Capiz" },
    { name: "Sanga-Sanga Airport (Tawi-Tawi Airport)", code: "TWT", location: "Tawi-Tawi" },
    { name: "San Jose Airport", code: "SJI", location: "Occidental Mindoro" },
    { name: "San Vicente Airport", code: "SWL", location: "San Vicente" },
    { name: "Sangley Point Airport", code: "SGL", location: "Cavite" },
    { name: "Sayak Airport (Siargao Airport)", code: "IAO", location: "Siargao" },
    { name: "Subic Bay International Airport", code: "SFS", location: "Morong" },
    { name: "Surigao Airport", code: "SUG", location: "Surigao City" },
    { name: "Tandag Airport", code: "TDG", location: "Tandag" },
    { name: "Tugdan Airport", code: "TBH", location: "Romblon" },
    { name: "Tuguegarao Airport", code: "TUG", location: "Tuguegarao" },
    { name: "Virac Airport", code: "VRC", location: "Catanduanes" },
    { name: "Zamboanga International Airport", code: "ZAM", location: "Zamboanga City" }
  ];